name: Build My APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Android Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev python3-setuptools libportmidi-dev

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Python Packages
        run: |
          pip install --upgrade pip
          pip install flet pygame

      - name: Build APK with Flet
        run: flet build apk
        continue-on-error: true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: volt-jump-apk
          path: build/apk/*.apk
